# Site settings
title: Primitives
lang: en-US

description: Engineering Blog
header_img: /assets/img/home.jpeg

baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

owner: manifoldfinance
published_at: 2022
repository: manifoldfinance/primitives

# Sidebar settings
sidebar: true
sidebar_avatar: /assets/img/avatar.jpeg
sidebar_about_description:
  Engineering blog for Ethereum, Systems and Mechanism design and architecture

RSS: true
email: sam@manifoldfinance.com
github_username: manifoldfinance
# Publish posts or collection documents with a future date.
future: true
twitter_username: foldfinance

# Google Analytics settings (https://analytics.google.com/)
ga_measurement_id:

# Comments settings (https://utteranc.es/)
# You must use your own repository, otherwise it won't work.
#comments_repository: manifoldfinance/comments


# Build settings
paginate: 10
timezone: US/Pacific
highlighter: rouge
permalink: pretty


anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



collections:
  pages:
    output: true
    permalink: /:path
defaults:
  - scope:
      path: _posts
    values:
      layout: post

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - rouge
  - jekyll-katex


# Blog archives
#
# Docs: https://github.com/jekyll/jekyll-archives/
jekyll-archives:
  enabled:
    - year
  layout: posts-year
  permalinks:
    year: '/:year/'


# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
[
  { title: "BLOG_1", href: "#" },
  { title: "NEWSLETTER_1", href: "#" },
  { title: "BLO_2", href: "http://manifoldfinance.com" },
]