# Site settings
title: Primitives
lang: en-US

description: Engineering Blog
header_img: /assets/img/home.jpeg

owner: manifoldfinance
published_at: 2022
repository: manifoldfinance/primitives

# Sidebar settings
sidebar: true
sidebar_avatar: /assets/img/avatar.jpeg
sidebar_about_description:
  Engineering blog for Ethereum, Systems and Mechanism design and architecture

RSS: true
email: sam@manifoldfinance.com
github_username: manifoldfinance
# Publish posts or collection documents with a future date.
future: true
twitter_username: foldfinance

# Google Analytics settings (https://analytics.google.com/)
ga_measurement_id:

# Comments settings (https://utteranc.es/)
# You must use your own repository, otherwise it won't work.
#comments_repository: manifoldfinance/comments


# Build settings
paginate: 10
timezone: US/Pacific
highlighter: rouge
permalink: pretty
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`

markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  pages:
    output: true
    permalink: /:path
defaults:
  - scope:
      path: _posts
    values:
      layout: post

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - rouge
  - jekyll-katex


# Blog archives
#
# Docs: https://github.com/jekyll/jekyll-archives/
jekyll-archives:
  enabled:
    - year
  layout: posts-year
  permalinks:
    year: '/:year/'

# Friends
friends: [
  { title: "BLOG_1", href: "http://manifoldfinance.com" },
  { title: "NEWSLETTER_1", href: "http://manifoldfinance.com" },
  { title: "BLO_2", href: "http://manifoldfinance.com" },
]

exclude: [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    ".github/",
    "Makefile",
    "dev-server",
    "configure",
    "webpack.config.js",
    "yarn.lock",
    "Gemfile.lock" ,
    "*.sh"
]
