# Site settings
title: Primitives
description: Engineering Blog
header_img: /assets/img/home.jpeg
baseurl: /primitives
owner: manifoldfinance
published_at: 2022
repository: manifoldfinance/primitives

# Sidebar settings
sidebar: true
sidebar_avatar: /assets/img/avatar.jpeg
sidebar_about_description: 0xJanitor

RSS: true
email: sam@manifoldfinance.com
github_username: manifoldfinance

# Google Analytics settings (https://analytics.google.com/)
ga_measurement_id:

# Comments settings (https://utteranc.es/)
# You must use your own repository, otherwise it won't work.
#comments_repository: manifoldfinance/comments

# Build settings
paginate: 10
timezone: UTC
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter_opts:
    block:
      line_numbers: true
collections:
  pages:
    output: true
    permalink: /:path/
defaults:
  - scope:
      path: _posts
    values:
      layout: post
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - rouge
